PREFIX rdf:  <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX fx:   <http://sparql.xyz/facade-x/ns/>
PREFIX xyz:  <http://sparql.xyz/facade-x/data/>
PREFIX organs: <http://w3id.org/polifonia/resource/organs/>
PREFIX organ: <http://w3id.org/polifonia/ontology/organs/>
PREFIX core: <https://w3id.org/polifonia/ontology/core/>
PREFIX ins: <http://w3id.org/polifonia/ontology/instrument/>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>

construct {

    # Division
    ?division_type_iri a organ:DivisionType ;
        core:name ?division_type_name ;
        core:refersTo organ:OrganDivision .

}
WHERE {

    SERVICE <x-sparql-anything:> {

        fx:properties fx:location ?_filepath . 
    
        ?division_base_root a fx:root ;
            ?division_slot ?division_type_name .

        BIND(IRI(replace(str(?division_slot), str(xyz:), str(organs:))) AS ?division_type_iri)

    }

}
