PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX core:  <https://w3id.org/polifonia/ontology/core/>
PREFIX organs: <http://w3id.org/polifonia/resource/organs/>
PREFIX organ: <http://w3id.org/polifonia/ontology/organs/>

SELECT DISTINCT ?external_url
WHERE {
    ?organ_query_iri a organ:Organ ;
    core:description ?external_url .

    VALUES ?organ_query_iri {
        organs:Part15_021AlphenaandenRijn
        organs:OI-ee4e8485b89314b0555e15c5b0b7181c
        organs:FR-67462-SELES-STFOYY1-X
    }
}